# Generated by Django 5.1.4 on 2025-01-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artisanmarket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uername', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField(unique=True)),
                ('pasword', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
