# Generated by Django 5.1.4 on 2025-01-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artisanmarket', '0002_user_delete_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pasword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='uername',
            new_name='username',
        ),
    ]
