# Generated by Django 5.1.4 on 2025-01-07 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artisanmarket', '0003_rename_pasword_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('productdetails', models.CharField(max_length=100)),
                ('actual_price', models.BigIntegerField(null=True)),
                ('offer_price', models.BigIntegerField(null=True)),
                ('category', models.CharField(max_length=5)),
                ('quantity', models.IntegerField(null=True)),
                ('image1', models.CharField(max_length=100)),
                ('image2', models.CharField(max_length=100)),
                ('image3', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artisanmarket.user')),
            ],
        ),
    ]
