# Generated by Django 5.1.4 on 2025-01-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artisanmarket', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
