# Generated by Django 5.1.4 on 2025-01-28 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artisanmarket', '0008_rename_type_product_types_alter_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artisanmarket.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artisanmarket.user')),
            ],
        ),
    ]
