# Generated by Django 5.1.5 on 2025-02-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artisanmarket', '0009_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
